# Generated by Django 5.0.1 on 2024-02-21 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('batch_id', models.AutoField(primary_key=True, serialize=False)),
                ('batch_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('branch_id', models.AutoField(primary_key=True, serialize=False)),
                ('branch_name', models.CharField(max_length=100, unique=True)),
                ('branch_code', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('scheme_id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('schema_evaluation', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('std_id', models.AutoField(primary_key=True, serialize=False)),
                ('std_name', models.CharField(max_length=100, unique=True)),
                ('std_usn', models.CharField(max_length=10, unique=True)),
                ('sec', models.CharField(max_length=10)),
                ('sem', models.IntegerField()),
                ('roll_no', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('mobile', models.CharField(max_length=15)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance_app.batch')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance_app.branch')),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('sub_id', models.AutoField(primary_key=True, serialize=False)),
                ('sub_code', models.CharField(max_length=100, unique=True)),
                ('sub_name', models.CharField(max_length=100, unique=True)),
                ('subject_credit', models.IntegerField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance_app.branch')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.AutoField(primary_key=True, serialize=False)),
                ('staff_name', models.CharField(max_length=100, unique=True)),
                ('staff_code', models.CharField(max_length=100, unique=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance_app.branch')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance_app.subjects')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('lar', models.IntegerField()),
                ('sec', models.CharField(max_length=10)),
                ('attendance', models.CharField(max_length=100)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance_app.batch')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance_app.branch')),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance_app.schema')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance_app.staff')),
                ('std_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance_app.students')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance_app.subjects')),
            ],
        ),
    ]
