# Generated by Django 5.0.1 on 2024-03-03 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='lar',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='schema',
        ),
        migrations.AddField(
            model_name='attendance',
            name='sem',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='sec',
            field=models.CharField(max_length=2),
        ),
    ]
