# Generated by Django 5.0.1 on 2024-03-03 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0002_remove_attendance_lar_remove_attendance_schema_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='staff',
        ),
    ]
